### ISSUE TITLE
Cannot the quickstart nor any of the examples on https://carton.pub/

### ISSUE THREAD

**Issue by bramhoven** [VivekPanyam/carton#168]
I cannot seem to run any of the examples shown on [https://carton.pub/](https://carton.pub/).

For example I tried `bert-base-uncased`:
```
import cartonml as carton

# A permalink to the model
MODEL_URL = "https://carton.pub/google-research/bert-base-uncased/5f26d87c5d82b7c37ebf92fcb38788a063d49a64cfcf1f9d118b3b710bb88005"

async def main():
    # Load the model
    model = await carton.load(MODEL_URL)

    # Set up inputs
    inputs = {
        "input": await model.info.examples[0].inputs["input"].get(),
    }

    # Run the model
    results = await model.infer(inputs)

    # Print the results
    print(results)

    # Print the expected results
    print({
        "tokens": await model.info.examples[0].sample_out["tokens"].get(),
        "scores": await model.info.examples[0].sample_out["scores"].get(),
    })

import asyncio
asyncio.run(main())
```

And the result I get is:
```
(carton-tests) ➜  carton-tests python main.py
Request: 0 67584
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid value: integer `1281`, expected variant index 0 <= i < 6")', /app/source/carton-runner-interface/src/do_not_modify/framed.rs:41:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I also tried `distilbert-base-cased-distilled-squad` and that gave the same response.

Maybe I am doing something wrong or I might be missing some dependencies, but I haven't been able to figure it out yet.

**Comment by VivekPanyam** [comment]
Hmm that's odd. I just copied the code in your comment into a file and ran it:

```
{'scores': array([[18.199741],
       [12.977381]], dtype=float32), 'tokens': array([['capital'],
       ['day']], dtype='<U7')}
{'tokens': array([['capital'],
       ['day']], dtype='<U7'), 'scores': array([[18.19973 ],
       [12.977381]], dtype=float32)}
```

What platform are you on? (OS and arch)

Can you try wiping your runners directory and rerunning to see if that fixes it. This defaults to `~/.carton/runners/` (see https://carton.run/docs/config). 

(You're probably going to get a different error of `'String tensor output not implemented yet'`, but that's fixed in #167 which should be out in the next nightly build)

**Comment by bramhoven** [comment]
I am running Arch Linux x86_64.

After deleting the runners directory and rerunning it gives the same result:
```
(carton-tests) ➜  carton-tests python main.py
Request: 0 67584
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid value: integer `1281`, expected variant index 0 <= i < 6")', /app/source/carton-runner-interface/src/do_not_modify/framed.rs:41:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

**Comment by VivekPanyam** [comment]
Can you try `pip install --force-reinstall cartonml-nightly`?

**Comment by bramhoven** [comment]
Then I do get the error you were referring to:
```
(carton-tests) ➜  carton-tests python main.py
thread 'tokio-runtime-worker' panicked at 'String tensor output not implemented yet', source/carton-bindings-py/src/conversions.rs:580:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/bram/git/carton-tests/main.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bram/git/carton-tests/main.py", line 12, in main
    "input": await model.info.examples[0].inputs["input"].get(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_asyncio.RustPanic: rust future panicked
```

Thanks! :)

**Comment by VivekPanyam** [comment]
I am able to reproduce your original error if I install `cartonml-nightly==0.0.1.dev20230926`. This was released before Carton was open sourced (and importantly before #147 landed). That was a breaking change to the wire protocol, but as Carton wasn't open source and I was the only one with old runners/bindings, it wasn't worth keeping backwards compatibility (as described in the PR). 

I'm not sure how you had that version installed vs a newer one, but I'll yank the pre-open-source versions from PyPI just in case.

**Comment by VivekPanyam** [comment]
(FYI the nightly builds have completed successfully)

**Comment by bramhoven** [comment]
I just checked it and it works like a charm! :)
